### PR TITLE
add GE MRI

### PR DESCRIPTION
**Pull request by allaway**
For NFOSI-810

### CODE REVIEW

**Comment by allaway** [comment]
Converting this back to draft b/c I missed some things...

**Comment by allaway** [comment]
OK, this is actually ready for review now 😓

**Review by anngvu — COMMENTED** [review]
Summary of additional discussion: resolution for now is to keep as single value to retain dropdown with a special selection string value like "Disease1,Disease2,Disease3" until we have better UI.

**Comment by allaway** [comment]
> Summary of additional discussion: resolution for now is to keep as single value to retain dropdown with a special selection string value like "Disease1,Disease2,Disease3" until we have better UI.

Actually, I was thinking about just pushing the value "Disease1,Disease2,Disease3" "manually", ie w/o validation. But I could also add it as a value to the schema. I believe these contributors will not be adding more data to their project, which makes me lean towards the skip-validation approach (it's 3 files total). What do you think?

**Comment by allaway** [comment]
Actually, now that I think about it, if I'm skipping validation, should I just annotate it as a stringList anyway?

**Comment by anngvu** [comment]
@allaway Yeah, let's just annotate it as stringList for these 3 files then. We can skip adding the unwieldy "Disease1,Disease2,Disease3" since there's already human validation, technically.

**Comment by anngvu** [comment]
Superseded by #457

**Pull request closed without merging**
