### PR TITLE
add specimenID to bts:ProcessedAlignedReadsTemplate

### PR DESCRIPTION
**Pull request by allaway**
SpecimenID is useful here as it often contains info about different replicates, treatments, etc, in cell line sequencing

### CODE REVIEW

**Comment by allaway** [comment]
Hmm, not sure if I broke something or the tests are broken..

`ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/typing_extensions.py)`

**Review by anngvu — APPROVED** [review]
Thanks -- you can ignore the test results, there's suddenly some dependency issue on GH Actions

**Review by anngvu — CHANGES_REQUESTED** [review]
Actually, I just realized there may be another fix needed, since this inherits from BiologicalAssayDataTemplate, which has `specimenID` -- let me make suggestion

**Review by anngvu — APPROVED** [review]
OK, from my comments I see why it wasn't at that level originally -- all good!

**Comment by allaway** [comment]
> OK, from my comments I see why it wasn't at that level originally -- all good!
I went thru the exact same thought process! :) I am happy to move it up a level if that makes sense more generally. I can imagine other assays might benefit from specimenID info.

**Pull request merged**
