### PR TITLE
Create schematic-schema-convert.yml

### PR DESCRIPTION
**Pull request by allaway**
@anngvu, this PR adds a job to automatically build the jsonld file when changes are pushed to the csv. Let me know what you think/if this seems like a reasonable SOP going forward!

### CODE REVIEW

**Comment by allaway** [comment]
BTW, the most recent commit failed because there was no change to the csv (and thus no updated jsonld to commit). https://github.com/nf-osi/nf-metadata-dictionary/runs/5339259981?check_suite_focus=true is an example of a successful run.

**Comment by anngvu** [comment]
Suggestion: There may be cases where we're just updating LICENSE, README, docs. Maybe you can trigger this workflow only if `NF.csv` changes (instead of running it on no changes and getting an error). See official doc for the file/path filter [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths). Also [this example](https://github.com/nf-osi/jobs/blob/main/.github/workflows/docker-update.yml) of using the path filter to make workflow more specific.

**Comment by allaway** [comment]
@anngvu , great idea! Done.

**Comment by anngvu** [comment]
Awesome!

**Pull request merged**
