### PR TITLE
Update props.yaml

### PR DESCRIPTION
**Pull request by cconrad8**
to correct the warning that is given when age is blank.  

adding '- required ' should ignore the validation rule of number if there is nothing entered

### CODE REVIEW

**Comment by cconrad8** [comment]
Hmmm @anngvu how do I add validation rules properly?

**Comment by cconrad8** [comment]
In Gray Foundation it looks like we use something like this, but here I used `pattern:` which i found on linkml docs . Thoughts on what the correct syntax is?

   ```
 annotations:
      validationRules: regex match ^\d*\.?\d*$|^unknown$
```

**Comment by anngvu** [comment]
@cconrad8 

- For validation rules in general: Use schematic syntax documented in Confluence -- it does make things a lot easier to remember and consistent with all schematic requirements. I'll add a note about that in the README.
- More specifically in this case: I don't think it makes sense that schematic is outputting warnings that "age is not a num" when age is not required and the age field is blank... so it shouldn't be fixed by us changing validation to regex, it should be fixed in schematic.

**Review by anngvu — COMMENTED** [review]
Added explanation why not recommended

**Pull request closed without merging**
