### PR TITLE
add oncotree terms

### LINKED ISSUE #102: change Low Grade Glioma to Low-Grade Glioma, NOS
**Describe the issue with the metadata**
In the interest of moving towards ONCOTREE for tumor types, it would be good to convert tumorType =  Low Grade Glioma to `Low-Grade Glioma, NOS`. The Synodos LGG project specifies different gliomas, such as pilocytic astrocytoma, but some tumors are just" Low-Grade Glioma, NOS".

We do have some files that map to the term [Low Grade Glioma](https://www.synapse.org/#!Synapse:syn16858331/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjE2ODU4MzMxIHdoZXJlIHR1bW9yVHlwZSBsaWtlICclTG93IEdyYWRlIEdsaW9tYSUnIiwgImFkZGl0aW9uYWxGaWx0ZXJzIjpbXSwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1LCAic29ydCI6W119) so we would need to remap these. 

**List alternative**
Code: LGGNOS
Name: Low-Grade Glioma, NOS
Main type: Glioma
NCI: Not Available
UMLS: Not Available
Color: Gray

**Additional comments**
One benefit to moving to ONCOTREE is interoperability with TCGA, HTAN, NCIT, UMLS (well, not for the last two for this example....)

### PR DESCRIPTION
**Pull request by allaway**
Closes #102, which is a non backwards compatible changes. 

Adds the following terms from ONCOTREE for the Synodos LGG project: 
Pilocytic Astrocytoma
Low Grade Glioma, NOS
Pilomyxoid Astrocytoma
Diffuse Astrocytoma
Glioblastoma Multiforme
Anaplastic Pilocytic Astrocytoma
Pleomorphic Xanthoastrocytoma
Oligoastrocytoma
High-Grade Glioma, NOS
Unknown

Adds the following libraryPreparationMethod:
Illumina TruSeq DNA Nano

Since I was working on tumorTypes already, I also tossed out a bunch of tumor values (mainly blood cancers) that are not currently used in any Portal files. This should help if we decide to import ONCOTREE wholesale down the road, because many of these would need to be changed. 

When available, I converted the remaining terms to ONCOTREE values. The terms didn't actually need to change, just needed to update description to ONCOTREE abbreviation and change source. 

Since I was already making a non b/w compatible change with #102, I also changed `teratoma`, to the ONCOTREE `Teratoma`. 

After this is merged, can remap all instances of Low Grade Glioma to `Low Grade Glioma, NOS` and teratoma to `Teratoma`.

### CODE REVIEW

**Comment by allaway** [comment]
I also reorganized the CSV a bit to bring the tumorTypes into one block, and to bring the libraryPreparationMethods into one block.

**Comment by anngvu** [comment]
OK, I only regenerated the docs so the new tumor terms are updated.

**Comment by allaway** [comment]
Oops, sorry, I thought that CI handled that? What should I do in the future to make sure the docs are updated?

**Comment by anngvu** [comment]
Oh, np. Just go to `docs/index.Rmd` and hit "Knit" -- so it works more like [nfosi/research](https://github.com/nf-osi/research/) right now.

**Comment by allaway** [comment]
Sounds good, thanks!

**Comment by allaway** [comment]
For posterity: 

> After this is merged, can remap all instances of Low Grade Glioma to Low Grade Glioma, NOS and teratoma to Teratoma.

is done

**Pull request merged**
