### PR TITLE
Review and update boolean annotations in use (related to #141)

### LINKED ISSUE #141: Convert boolean true/false values to yes/no in schema
**Describe the issue with the metadata**
As we discussed in stand-up today there are a couple of good reasons for converting boolean values to yes/no values
- user feedback from our community indicates yes/no is more relatable/digestible than booleans 
- our all-caps `BOOLEANS` are converted to python `Booleans` by schematic `associateMetadataWithFiles()` or by synapseclient - not sure which - but either way, this results in the Booleans not passing validation during re-annotation, and also doesn't comply with our schema. `yes`/`no` values should not have this coercion issue. 

Note: all of our boolean annotations will need to be updated on the portal as well!

### PR DESCRIPTION
**Pull request by anngvu**

### CODE REVIEW

**Review by allaway — CHANGES_REQUESTED** [review]
In general looks good to me. There's also the `failedQC` boolean. Do we want to leave that as-is or change it for consistency?

**Comment by anngvu** [comment]
@allaway Updated `failedQC` as suggested and will merge.

**Comment by anngvu** [comment]
@allaway Updated `failedQC` as suggested and will merge.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74316131](https://www.synapse.org/#!Synapse:syn74316131)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Meningiomas in patients with neurofibromatosis type 2 predominantly comprise the 'immunogenic' subtype |
| diseaseFocus | Neurofibromatosis type 2 |
| manifestation | Schwannoma |
| dataType | geneExpression |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Meningioma |
| diagnosis | Neurofibromatosis 2 |
| platform | Illumina |
| studyLeads | Yu Teranishi, Nobuhito Saito |
| institutions | University of Tokyo Graduate School of Medicine |
| pmid | 37752594 |
| doi | 10.1186/s40478-023-01645-3 |
| alternateDataRepository | geo:GSE232528, insdc.sra:PRJNA972676 |

### Curation Notes
- RNA-seq of NF2-associated meningiomas; immunogenic subtype classification
- 2 FASTQ files in Raw Data folder
- manifestation corrected: removed Neurofibroma and JMML (wrong for NF2 meningioma paper)

**Status:** pendingReview ✓

**Pull request merged**
